# vim: set expandtab ts=2 sw=2:
---
puppet-syntax:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake syntax
puppet-lint:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  allow_failure: true
  script:
    - bundle install
    - bundle exec rake lint
puppet-metadata:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake metadata
unit-test-ruby-2.1:
  stage: test
  tags:
    - beaker
  image: ruby:2.1
  before_script:
    - vagrant up
    - bundle install --path=vendor --no-binstubs
  script:
    - bundle exec rake spec
  after_script:
    - vagrant destroy -f
unit-test-ruby-2.3:
  stage: test
  tags:
    - beaker
  image: ruby:2.3
  before_script:
    - vagrant up
    - bundle install --path=vendor --no-binstubs
  script:
    - bundle exec rake spec
  after_script:
    - vagrant destroy -f
acceptance-test:
  stage: test
  tags:
    - beaker
  script:
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake acceptance
